name: 'Check Files'
description: 'Checks modified files to determine if tests should be run'
outputs:
  validate_orbit_chains:
    description: "Should Orbit chains be validated"
    value: ${{ steps.check-files.outputs.validate_orbit_chains }}
  run_tests:
    description: 'Whether tests should be run based on modified files'
    value: ${{ steps.check-files.outputs.run_tests }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Check modified files
      id: check-files
      shell: bash
      run: |
        echo "=============== list modified files ==============="
        files=`git diff --name-only HEAD^ HEAD`
        echo "$files"

        run_tests=false
        validate_orbit_chains=false

        for file in $files; do
          if [[ "$file" == */orbitChainsData.json || "$file" == packages/scripts/addOrbitChain/* ]]; then
            validate_orbit_chains=true
            break
          fi
        done

        for file in $files; do
          if [[ $file == packages/arb-token-bridge-ui/* ]]; then
            # Dont run e2e if only images/docs were changed
            if [[ $file =~ \.(md|svg|png|webp|gif|txt)$ ]]; then
              continue
            fi
            run_tests=true
            break
          fi
        done

        echo "validate_orbit_chains=$validate_orbit_chains" >> $GITHUB_OUTPUT
        echo "run_tests=$run_tests" >> $GITHUB_OUTPUT
