name: 'Check Files'
description: 'Checks modified files to determine if tests should be run'
outputs:
  run_tests:
    description: 'Whether tests should be run based on modified files'
    value: ${{ steps.check-files.outputs.run_tests }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Check modified files
      id: check-files
      shell: bash
      run: |
        echo "=============== list modified files ==============="
        files=`git diff --name-only HEAD^ HEAD`
        echo "$files"
        for file in $files; do
          if [[ $file != packages/* ]] && ! [[ $file =~ .*\.(lock|yml)$ ]]; then
            # if not in packages/ and does not end with .lock or .yml
            echo "run_tests=false" >> $GITHUB_OUTPUT
          elif [[ $file == .github/ISSUE_TEMPLATE/* ]]; then
            echo "run_tests=false" >> $GITHUB_OUTPUT
          elif [[ $file =~ .*\.(md|svg|png|webp|gif|txt)$ ]]; then
            echo "run_tests=false" >> $GITHUB_OUTPUT
          else
            echo "run_tests=true" >> $GITHUB_OUTPUT
            break
          fi
        done