name: 'Update Check Run'
description: 'Create or update a check run for CCTP E2E Tests'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  status:
    description: 'Status of the check run (in_progress or completed)'
    required: true
  conclusion:
    description: 'Conclusion of the check run (success, failure, etc.)'
    required: false
  details-url:
    description: 'URL for more details'
    required: false
runs:
  using: 'node20'
  main: 'index.js'