name: Restore build artifacts
description: Restore build artifacts

runs:
  using: composite
  steps:
    - name: Restore build artifacts
      uses: actions/cache/restore@v3
      with:
        path: |
          ./packages/arb-token-bridge-ui/build
        key: build-artifacts-${{ github.run_id }}
        fail-on-cache-miss: true
