version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .

  test-sdk:
    docker:
      - image: cimg/node:16.14.2-browsers
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn test:sdk

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test-sdk:
          requires:
            - build
