version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ checksum "yarn.lock" }}
            - v1-yarn-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
            # Wildcard paths are currently not supported.
            #
            # https://circleci.com/docs/2.0/configuration-reference/#save_cache
            - packages/arb-token-bridge-ui/node_modules
            - packages/token-bridge-sdk/node_modules
            - packages/use-wallet/node_modules
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  test-sdk:
    docker:
      - image: cimg/node:16.14.2-browsers
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn test:ci:sdk

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test-sdk:
          requires:
            - build
