name: Add Orbit Chain Request
description: File a request to have your Orbit chain added to the bridge
title: "[feat]: Add Orbit chain "
labels: ["feat", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        # Add an Orbit Chain to the Bridge UI
  - type: markdown
    attributes:
      value: |
        This form is used to submit a request to add an Orbit chain to the [Arbitrum bridge](https://bridge.arbitrum.io/). Please provide all the necessary config information. You can get all contract addresses by running [getAllContracts](https://github.com/OffchainLabs/arbitrum-orbit-sdk/blob/feat-add-verification-scripts/examples/verify-rollup/README.md#get-all-contracts).
  - type: input
    id: chain-id
    attributes:
      label: Chain ID
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Chain name
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Chain description
      description: |
        A short chain description that will be visible in the networks dropdown. Please make sure this is no longer than 130 characters.
      placeholder: ex. An amazing chain that does amazing things.
    validations:
      required: true
  - type: input
    id: brand-color
    attributes:
      label: Brand color
      description: The primary hex code color of your chain.
      placeholder: ex. "#FFFFFF"
    validations:
      required: true
  - type: input
    id: chain-logo
    attributes:
      label: Chain logo
      description: Link to the chain logo file.
    validations:
      required: true
  - type: input
    id: rpc-url
    attributes:
      label: RPC URL
    validations:
      required: true
  - type: input
    id: explorer-url
    attributes:
      label: Explorer URL
    validations:
      required: true
      
  - type: dropdown
    id: parent-chain-id
    attributes:
      label: Parent Chain ID
      description: Select the parent chain for your Orbit chain.
      options:
        - "1"
        - "42161"
        - "421614"
        - "11155111"
        - "17000"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Native token information
  - type: markdown
    attributes:
      value: |
        Fill out this section if you are using a native token other than ETH. If you are using ETH as your gas token you can leave this blank.
  - type: input
    id: native-token-address
    attributes:
      label: Native token address
      placeholder: ex. 0x0000000000000000000000000000000000000000
    validations:
      required: false
  - type: input
    id: native-token-name
    attributes:
      label: Native token name
      placeholder: ex. Ether
    validations:
      required: false
  - type: input
    id: native-token-symbol
    attributes:
      label: Native token symbol
      placeholder: ex. ETH
    validations:
      required: false
  - type: input
    id: native-token-logo
    attributes:
      label: Native token logo
      description: Link to the native token logo file.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Chain Configuration and Core Addresses
  - type: markdown
    attributes:
      value: |
        Please fill out this section with your chain configuration details and contract addresses. As a reminder, you can get all contract addresses by running [getAllContracts](https://github.com/OffchainLabs/arbitrum-orbit-sdk/blob/feat-add-verification-scripts/examples/verify-rollup/README.md#get-all-contracts).
  - type: input
    id: confirmPeriodBlocks
    attributes:
      label: confirmPeriodBlocks
      placeholder: ex. 45818
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Rollup contract addresses
  - type: markdown
    attributes:
      value: |
        You can find this information under the `"coreContracts" : {...}` key.
  - type: input
    id: bridge
    attributes:
      label: bridge
    validations:
      required: true    
  - type: input
    id: inbox
    attributes:
      label: inbox
    validations:
      required: true
  - type: input
    id: outbox
    attributes:
      label: outbox
    validations:
      required: true
  - type: input
    id: rollup
    attributes:
      label: rollup
    validations:
      required: true
  - type: input
    id: sequencerInbox
    attributes:
      label: sequencerInbox
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Parent chain token bridge contract addresses
  - type: markdown
    attributes:
      value: |
        You can find this information under the `"l2Contracts" : {...}` key.
  - type: input
    id: parent-custom-gateway
    attributes:
      label: Parent Custom Gateway
    validations:
      required: true
  - type: input
    id: parent-erc20-gateway
    attributes:
      label: Parent ERC20 Gateway
    validations:
      required: true
  - type: input
    id: parent-gateway-router
    attributes:
      label: Parent Gateway Router
    validations:
      required: true
  - type: input
    id: parent-multicall
    attributes:
      label: Parent MultiCall
    validations:
      required: true
  - type: input
    id: parent-proxy-admin
    attributes:
      label: Parent Proxy Admin
    validations:
      required: true
  - type: input
    id: parent-weth
    attributes:
      label: Parent WETH
    validations:
      required: true
  - type: input
    id: parent-weth-gateway
    attributes:
      label: Parent WETH Gateway
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Orbit chain token bridge contract addresses 
  - type: markdown
    attributes:
      value: |
        You can find this information under the `"l3Contracts" : {...}` key.
  - type: input
    id: child-custom-gateway
    attributes:
      label: Child Custom Gateway
    validations:
      required: true
  - type: input
    id: child-erc20-gateway
    attributes:
      label: Child ERC20 Gateway
    validations:
      required: true
  - type: input
    id: child-gateway-router
    attributes:
      label: Child Gateway Router
    validations:
      required: true
  - type: input
    id: child-multicall
    attributes:
      label: Child Multicall
    validations:
      required: true
  - type: input
    id: child-proxy-admin
    attributes:
      label: Child Proxy Admin
    validations:
      required: true
  - type: input
    id: child-weth
    attributes:
      label: Child WETH
    validations:
      required: true
  - type: input
    id: child-weth-gateway
    attributes:
      label: Child WETH Gateway
    validations:
      required: true
