name: Add Layer Leap Request
description: File a request to have your Orbit chain support Layer Leap transfers
title: "[feat]: enable Layer Leap for <Orbit Chain>"
labels: ["feat", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the necessary config information for the Orbit chain.
  - type: input
    id: chain-id
    attributes:
      label: Chain ID
      placeholder: Your Orbit Chain ID
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Chain name
      placeholder: Your Orbit Chain name
    validations:
      required: true
  - type: input
    id: parent-chain-id
    attributes:
      label: Parent chain ID
      placeholder: eg. 42161
    validations:
      required: true
  - type: input
    id: parent-chain-name
    attributes:
      label: Parent Chain name
      placeholder: eg. Arbitrum One
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: |
        Native token information - only fill this if you are using a native token other than ETH
  - type: input
    id: native-token-address
    attributes:
      label: Native token address
      placeholder: eg. 0x0000000000000000000000000000000000000000
    validations:
      required: false
  - type: input
    id: native-token-name
    attributes:
      label: Native token name
      placeholder: eg. Ether
    validations:
      required: false           
  - type: input
    id: native-token-symbol
    attributes:
      label: Native token symbol
      placeholder: eg. ETH
    validations:
      required: false


  - type: markdown
    attributes:
        value: |
          Information for enabling Layer Leap transfers for your Orbit Chain
  - type: checkboxes
    attributes:
      label: Enable Layer Leap
      options:
        - label: We would like to adopt Layer Leap on bridge.arbitrum.io
          required: true
  - type: input
    id: layerleap-token-symbol
    attributes:
      description: ERC20 tokens listed here will be added to an allowlist for L1-to-L3 ERC20 transfers
      label: Token symbol(s) to allow Layer Leap for (Comma-separated, if multiple)
      placeholder: eg. WETH, LINK, etc.
    validations:
      required: true
  - type: input
    id: layerleap-token-addresses
    attributes:
      description: ERC20 addresses (L1) listed here will be added to an allowlist for L1-to-L3 ERC20 transfers (should correspond to the symbols above)
      label: L1 token address(es) to allow Layer Leap for (Comma-separated, if multiple)
      placeholder: eg. 0xfff9976782d46cc05630d1f6ebab18b2324d6b14, 0x779877A7B0D9E8603169DdbD7836e478b4624789
    validations:
      required: true
