name: Add Orbit Chain Request
description: File a request to have your Orbit chain added to the bridge
title: "[feat]: Add Orbit chain "
labels: ["Type: Add Orbit Chain"]
body:
  - type: markdown
    attributes:
      value: |
        # Add an Orbit Chain to the Bridge UI
  - type: markdown
    attributes:
      value: |
        This form is used to submit a request to add an Orbit chain to the [Arbitrum bridge](https://bridge.arbitrum.io/). Please provide all the necessary config information. You can get all contract addresses by running [getAllContracts](https://github.com/OffchainLabs/arbitrum-orbit-sdk/blob/feat-add-verification-scripts/examples/verify-rollup/README.md#get-all-contracts).
  - type: input
    id: raas-provider
    attributes:
      label: Who is your RaaS Provider?
    validations:
      required: true
  - type: input
    id: chain-id
    attributes:
      label: Chain ID
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Chain name
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Chain description
      description: |
        A short chain description that will be visible in the networks dropdown.
      placeholder: ex. An amazing chain that does amazing things.
    validations:
      required: false
  - type: input
    id: brand-color
    attributes:
      label: Brand color
      description: The primary hex code color of your chain. Must have a contrast ratio of at least 3:1 against white (#FFFFFF) for accessibility.
      placeholder: ex. "#FFFFFF"
    validations:
      required: true
  - type: textarea
    id: chain-logo
    attributes:
      label: Chain logo
      description: |
        Please drag and drop your chain logo image here. Supported formats: PNG, SVG, JPG, JPEG, WEBP. Images larger than 100KB will be resized.
      placeholder: Drag and drop your chain logo image here...
    validations:
      required: true
  - type: input
    id: rpc-url
    attributes:
      label: RPC URL
    validations:
      required: true
  - type: input
    id: explorer-url
    attributes:
      label: Explorer URL
    validations:
      required: true
      
  - type: dropdown
    id: parent-chain-id
    attributes:
      label: Parent chain ID
      description: Select the parent chain for your Orbit chain.
      options:
        - "1"
        - "42161"
        - "42170"
        - "421614"
        - "11155111"
        - "17000"
        - "8453"
        - "84532"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Native token information
  - type: markdown
    attributes:
      value: |
        Fill out this section if you are using a native token other than ETH. 
         ⚠️ IMPORTANT: If you are using ETH as your gas token you can leave this blank.
  - type: input
    id: native-token-address
    attributes:
      label: Native token address on Parent Chain
      placeholder: ex. 0x0000000000000000000000000000000000000000
    validations:
      required: false
  - type: input
    id: native-token-name
    attributes:
      label: Native token name
      placeholder: ex. My Custom Token
    validations:
      required: false
  - type: input
    id: native-token-symbol
    attributes:
      label: Native token symbol
      placeholder: ex. MCT
    validations:
      required: false
  - type: textarea
    id: native-token-logo
    attributes:
      label: Native token logo
      description: |
        Please drag and drop your native token logo image here. Supported formats: PNG, SVG, JPG, JPEG, WEBP. Images larger than 100KB will be resized.
      placeholder: Drag and drop your native token logo image here (skip if using ETH)...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Chain Configuration and Core Addresses
  - type: markdown
    attributes:
      value: |
        Please fill out this section with your chain configuration details and contract addresses. As a reminder, you can get all contract addresses by running [getAllContracts](https://github.com/OffchainLabs/arbitrum-orbit-sdk/blob/feat-add-verification-scripts/examples/verify-rollup/README.md#get-all-contracts).

  - type: markdown
    attributes:
      value: |
        ## Rollup contract address
  - type: markdown
    attributes:
      value: |
        You can find this information under the `"coreContracts" : {...}` key.
  - type: input
    id: rollup
    attributes:
      label: rollup
      description: Please provide the address of the rollup contract. Other core contract addresses will be fetched automatically.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Parent chain token bridge contract addresses
  - type: input
    id: parent-custom-gateway
    attributes:
      label: Parent Custom Gateway
    validations:
      required: true
  - type: input
    id: parent-erc20-gateway
    attributes:
      label: Parent ERC20 Gateway
      description: This is also called the standard gateway. [Read more](https://docs.arbitrum.io/build-decentralized-apps/token-bridging/token-bridge-erc20#default-standard-bridging).
    validations:
      required: true
  - type: input
    id: parent-gateway-router
    attributes:
      label: Parent Gateway Router
    validations:
      required: true
  - type: input
    id: parent-multicall
    attributes:
      label: Parent MultiCall
    validations:
      required: true
  - type: input
    id: parent-weth
    attributes:
      label: Parent WETH
    validations:
      required: true
  - type: input
    id: parent-weth-gateway
    attributes:
      label: Parent WETH Gateway
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Orbit chain token bridge contract addresses 
  - type: input
    id: child-custom-gateway
    attributes:
      label: Child Custom Gateway
    validations:
      required: true
  - type: input
    id: child-erc20-gateway
    attributes:
      label: Child ERC20 Gateway
      description: This is also called the standard gateway. [Read more](https://docs.arbitrum.io/build-decentralized-apps/token-bridging/token-bridge-erc20#default-standard-bridging).
    validations:
      required: true
  - type: input
    id: child-gateway-router
    attributes:
      label: Child Gateway Router
    validations:
      required: true
  - type: input
    id: child-multicall
    attributes:
      label: Child MultiCall
    validations:
      required: true
  - type: input
    id: child-weth
    attributes:
      label: Child WETH
    validations:
      required: true
  - type: input
    id: child-weth-gateway
    attributes:
      label: Child WETH Gateway
    validations:
      required: true

  - type: dropdown
    id: fast-withdrawal
    attributes:
      label: Fast Withdrawals active
      description: Only select Yes if your chain has Fast Withdrawals enabled. We will show information in our UI that your chain has Fast Withdrawals implemented and that withdrawals will take less time than usual.
      options:
        - "No"
        - "Yes"
      default: 0
  - type: input
    id: fast-withdrawal-time
    attributes:
      label: Fast Withdrawals time in minutes
      description: Only fill this if your chain has Fast Withdrawals enabled.
      placeholder: ex. 1440
    validations:
      required: false

  - type: input
    id: launch-date
    attributes:
      label: Launch Date
      description: When is the chain expected to go live on the bridge? (YYYY-MM-DD) Leave empty if the the chain is already live.
      placeholder: ex. 2023-12-31
    validations:
      required: false
