name: Restore build artifacts	
description: Restore build artifacts	

runs:	
  using: composite	
  steps:	
    - name: Restore build artifacts	
      uses: actions/cache/restore@v4	
      with:	
        path: |	
          ./packages/app/build	
        key: build-artifacts-${{ github.run_id }}	
        fail-on-cache-miss: true	
