name: Download build artifacts
description: Download build artifacts

runs:
  using: composite
  steps:
    - name: Download build artifacts
      uses: actions/cache/restore@v3
      with:
        path: ./packages
        fail-on-cache-miss: true
        key: build-artifacts-${{ github.run_id }}-${{ github.run_attempt }}
