name: Download build artifacts
description: Download build artifacts

runs:
  using: composite
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: ./packages
