// export { fetchETHDepositsFromEventLogs } from './fetchETHDepositsFromEventLogs'
export { fetchETHDepositsFromSubgraph } from './fetchETHDepositsFromSubgraph'
// export { fetchTokenDepositsFromEventLogs } from './fetchTokenDepositsFromEventLogs'
export { fetchTokenDepositsFromSubgraph } from './fetchTokenDepositsFromSubgraph'
export type { FetchTokenDepositsFromSubgraphResult } from './fetchTokenDepositsFromSubgraph'
