name: 24-Hour Monitoring

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Run every 24 hours at midnight UTC

jobs:
  run-retryable-monitoring:
    strategy:
      matrix:
        chain: [core, orbit]
    uses: ./.github/workflows/monitoring.yml
    with:
      chain: ${{ matrix.chain }}
      monitor: retryable
    secrets: inherit
