name: Auto-Generate Denylist

on:
  workflow_dispatch:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node_modules
        uses: OffchainLabs/actions/node-modules/install@main

  generate:
    name: Generate
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3

      - name: Restore node_modules
        uses: OffchainLabs/actions/node-modules/restore@main

      - name: Generate denylist
        run: yarn generateDenylist

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'chore: update denylist'
          commit-message: 'chore: update denylist'
          base: master
          branch: chore-update-denylist
          delete-branch: true
