name: Retryable Monitor

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "3 8 * * *" # Run once a day at 08:03am GMT

jobs:
  run-retryable-monitoring:
    strategy:
      matrix:
        chain: [core, orbit]
    uses: ./.github/workflows/monitoring.yml
    with:
      chain: ${{ matrix.chain }}
      monitor: retryable
    secrets: inherit
