name: Scripts Test

on:
  pull_request:
    branches: ["master"]
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
  merge_group:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NEXT_PUBLIC_INFURA_KEY: ${{ secrets.NEXT_PUBLIC_INFURA_KEY }}
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID }}
  THE_GRAPH_NETWORK_API_KEY: ${{ secrets.THE_GRAPH_NETWORK_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-files:
    name: Check files
    runs-on: ubuntu-latest
    outputs:
      run_tests: ${{ steps.check-files.outputs.run_tests }}
      test_scripts: ${{ steps.check-files.outputs.test_scripts }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-files
        id: check-files

  test-scripts:
    name: "Test Scripts"
    runs-on: ubuntu-latest
    needs: [check-files]
    if: needs.check-files.outputs.test_scripts == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node_modules
        uses: OffchainLabs/actions/node-modules/install@main

      - name: Run scripts tests
        run: yarn workspace scripts test